version: '3.5'

services:

  #### BEGIN IMAGE ####

  spending_tracker:
    build:
      context: .
      dockerfile: dockerfile
    container_name: spending_tracker
    image: docker.io/ronhsienchang/spending_tracker:latest
    networks:
      - betfair-credit
    volumes:
      - ./src:/app:rw
      - ~/service_centre_static:/app/static:rw
    env_file: dev.env
    tty: true

  #### BEGIN SERVICE CENTRE NETWORK ####

networks:
  betfair-credit:
    name: betfair-credit
    driver: bridge
